src/Mutations/UpdateDraftEntrySignatureFieldValue.php

UpdateDraftEntrySignatureFieldValue now accepts empty string in case of deletion

---

src/Mutations/UpdateDraftEntryAddressFieldValue.php
src/Types/Input/AddressInput.php
src/WPGraphQLGravityForms.php

This PR adds the `UpdateDraftEntryAddressFieldValue` mutation.

Add UpdateDraftEntryAddressFieldValue mutation

---

src/Mutations/UpdateDraftEntryListFieldValue.php
src/Types/Field/FieldValue/ListFieldValue.php
src/Types/Field/FieldValue/ListInputValue.php
src/Types/Input/ListInput.php
src/WPGraphQLGravityForms.php

This PR adds the `UpdateDraftEntryListFieldValue` mutation.

Add UpdateDraftEntryListFieldValue mutation

---

src/Mutations/SubmitDraftEntry.php

Use GravityForm's API to send notifications if any are set on submit draft
entry mutation.
See #38

Trigger GF notifications on form submission

---

.phpcs.xml.dist
src/Connections/RootQueryEntriesConnectionResolver.php
src/DataManipulators/FieldsDataManipulator.php
src/DataManipulators/FormDataManipulator.php
src/Interfaces/Type.php
src/Mutations/DraftEntryUpdater.php
src/Types/Field/RadioField.php
src/Types/Union/ObjectFieldValueUnion.php

Various PHPCS fixes to doc-blocks and comments.

PHPCS fixes

---

src/Connections/EntryFieldConnection.php
src/Mutations/UpdateDraftEntryConsentFieldValue.php
src/Types/Entry/EntryForm.php
src/Types/Union/ObjectFieldValueUnion.php

This PR removes unnecessary `use` statements that the classes werent actually using.

Cleanup unnecesary class includes

---

CHANGELOG.md
README.md
wp-graphql-gravity-forms.php

version bump

---

composer.json
src/Utils/GFUtils.php
vendor/composer/InstalledVersions.php
vendor/composer/installed.json
vendor/composer/installed.php

Filters `GFUtils::get_form()` by `gform_pre_render`.
- feat: filter `GFUtils::get_form()` by `gform_pre_render`.
- dev: Add [WPGraphQL Stubs](https://github.com/Poolshark/wp-graphql-stubs) to dev dependencies.

Feat/filter form by gform_pre_render

---

README.md
docs/actions-and-filters.md
docs/recipes/register-custom-field-value-inputs.md
docs/recipes/register-custom-form-field.md
docs/recipes/register-form-to-custom-field.md

Fixes several typos and linkage in the docs.

docs: fix typos and linkage

---

CHANGELOG.md
README.md
readme.txt
wp-graphql-gravity-forms.php

Release: v0.10.1

---

src/Type/Enum/CurrencyEnum.php
src/Type/WPObject/Settings.php
src/Type/WPObject/Settings/Logger.php
src/Type/WPObject/Settings/Settings.php
src/Type/WPObject/Settings/SettingsLogging.php
src/TypeRegistry.php
tests/_support/Helper/GFHelpers/GFHelpers.php
tests/wpunit/SettingsTest.php
vendor/composer/autoload_classmap.php
vendor/composer/autoload_static.php
vendor/composer/installed.php

Adds GF settings to the schema.
Closes #200.
feat: Add `gfSettings` to the RootQuery.

Add GfSettings to schema

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/schema-linter.yml

- chore: Update .github templates.
- chore: fix schema linter GH action by setting explicit deps.

chore: update repo files

---

CHANGELOG.md
README.md
docs/actions-and-filters.md
docs/form-field-support.md
docs/querying-entries.md
src/Utils/Utils.php

docs: update action filters, pricing fields and composer usage, and minimum requirements  

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a checklist requirement to note PR changes in the changelog.

chore: update PR template with changelog requirement

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
src/Extensions/GFQuiz/Type/WPInterface/FieldChoiceSetting/ChoiceWithQuizChoices.php
src/Registry/FieldChoiceRegistry.php

Ensures `FormField.choices` correctly sets `$context->gfField`. Also fixes returned values for `FormQuizChoice.isCorrect` and `weight`.

fix: Ensure `FormField.choices` values resolve correctly.

---

CHANGELOG.md
composer.json
composer.lock
src/Extensions/GFQuiz/Type/WPObject/FormField/FieldProperty/PropertyMapper.php
src/Type/WPObject/FormField/FieldProperty/ChoiceMapper.php
vendor/composer/installed.php

Hotfix release addressing an issue with the `FormField.choices` resolver.
Currently, `QuizFieldChoice.isCorrect` and `weight` are sometimes returning incorrect values.
h/t @natac13 
- fix: `FormField.choices` doesn't always resolve values correctly.
- chore: replace abandoned `poolshark/wp-graphql-stubs` Composer dependency with `axewp/wp-graphql-stubs`.

release: 0.11.6

---

bin/_lib.sh

Spare 31×`--allow-root`
Nothing more.

Use WP_CLI_ALLOW_ROOT env variable

---

.github/workflows/code-quality.yml
.github/workflows/code-standard.yml
.github/workflows/integration-testing.yml
.github/workflows/schema-linter.yml
CHANGELOG.md
bin/run-docker.sh

Updates workflows to test against PHP 8.1
closes #299

ci: test against php 8.1

---

CHANGELOG.md
composer.lock
vendor/composer/ClassLoader.php
vendor/composer/autoload_real.php
vendor/composer/installed.php

updates dev dependencies to their latest versions.
Closes #354

chore: update dev deps

---

.github/workflows/integration-testing.yml
CHANGELOG.md
bin/run-docker.sh
docker-compose.yml
readme.txt
wp-graphql-gravity-forms.php

Updates the test matrix to include WP 6.2

ci: test against WordPress 6.2

---

.github/workflows/integration-testing.yml

ci: exclude php 8.1 for now

---

.github/workflows/code-quality.yml
.github/workflows/code-standard.yml
.github/workflows/integration-testing.yml
.github/workflows/schema-linter.yml
CHANGELOG.md
README.md
bin/_lib.sh
bin/run-docker.sh
composer.lock
docker-compose.yml
tests/_data/config.php
vendor/composer/installed.php

ci: silence PHP notices when codeception activates GF plugins

---

composer.json

Fix Composer configuration

---

CHANGELOG.md
composer.lock
vendor/composer/installed.php

Adds a changelog entry for #373 
Also rebuilds the lockfile.

chore: update lockfile and changelog

---

CHANGELOG.md
src/Extensions/GFQuiz/Type/WPObject/QuizResults/QuizResults.php
src/Type/WPObject/Form/Form.php

- fix: Check if entries exist before resolving the connection `count`.
- fix: Improve type checks when calculating the `QuizResults` data.
Reported downstream in harness-software/harness-api

fix: downstream bugfixes

---

.github/workflows/integration-testing.yml
CHANGELOG.md
bin/run-docker.sh
readme.txt
wp-graphql-gravity-forms.php

Tests the plugin against WP 6.4
Housekeeping

chore: test against WP 6.4

---

CHANGELOG.md
composer.json
composer.lock
src/Connection/AbstractConnection.php
src/Data/Connection/EntriesConnectionResolver.php
src/Data/EntryObjectMutation.php
src/Data/FieldValueInput/AbstractFieldValueInput.php
src/Data/FieldValueInput/CaptchaValueInput.php
src/Extensions/GFQuiz/Type/WPObject/QuizResults/QuizResults.php
src/Extensions/GFSignature/Data/FieldValueInput/SignatureValuesInput.php
src/Extensions/WPGatsby/GravityFormsMonitor.php
src/Extensions/WPJamstackDeployments/WPJamstackDeployments.php
src/Mutation/SubmitDraftEntry.php
src/Mutation/SubmitForm.php
src/Mutation/UpdateDraftEntry.php
src/Mutation/UpdateEntry.php
src/Type/AbstractType.php
src/Type/WPInterface/AbstractInterface.php
src/Type/WPInterface/Entry.php
src/Type/WPInterface/FieldChoiceSetting/AbstractFieldChoiceSetting.php
src/Type/WPInterface/FieldInputSetting/AbstractFieldInputSetting.php
src/Type/WPInterface/FieldSetting/FieldWithPostImage.php
src/Type/WPInterface/FieldWithChoices.php
src/Type/WPInterface/FormField.php
src/Type/WPObject/AbstractObject.php
src/UpdateChecker.php
src/Utils/GFUtils.php
vendor/composer/installed.php

This PR updates the composer dev-deps to their latest version, and then fixes the smells from wp-graphql-cs 2.0.0-beta.2

chore: update dev-deps and lint

---

CHANGELOG.md
README.md
docs/i18n.md

This PR adds a doc on handling i18n/l10n issues with schema generation.
Closes #372

docs: add i18n docs and fix changelog

---

.github/workflows/code-quality.yml
.github/workflows/code-standard.yml
.github/workflows/integration-testing.yml
.github/workflows/schema-linter.yml
CHANGELOG.md
README.md
bin/run-docker.sh
docker-compose.yml

ci: Test plugin compatibility with PHP 8.2.

---

CHANGELOG.md
wp-graphql-gravity-forms.php

Adds WPGraphQL as a plugin dependency header.
WP 6.5 Compatibility

feat: add plugin dependency header

---

CHANGELOG.md
phpstan/constants.php
vendor/composer/installed.php
wp-graphql-gravity-forms.php

release: 0.12.6

---

CHANGELOG.md
README.md
composer.json
composer.lock
docs/actions-and-filters.md
readme.txt
src/Data/Connection/EntriesConnectionResolver.php
src/Data/Connection/FormsConnectionResolver.php
tests/wpunit/EntryConnectionPaginationTest.php
tests/wpunit/FormConnectionQueriesTest.php
vendor/composer/installed.php
wp-graphql-gravity-forms.php

This PR:
- Updates the Composer deps
- Fixes test compatibility with wp-graphql-test-case 3.0.1
- Bumps minimum WPGraphQL version to 1.26.0

feat!: update connection resolvers

---

docs/querying-entries.md
docs/querying-formfields.md
docs/submitting-forms.md

Changes inline `**Note**` to GH's flavor of `>[!NOTE_TYPE]`
Improve doc readability

docs: use [!NOTE] syntax

---

CHANGELOG.md
src/Connection/AbstractConnection.php
src/Extensions/GFQuiz/Type/WPObject/QuizResults/QuizResultsFieldCount.php
src/Interfaces/Enum.php
src/Interfaces/Mutation.php
src/Interfaces/TypeWithConnections.php
src/Interfaces/TypeWithFields.php
src/Interfaces/TypeWithInputFields.php
src/Type/Enum/AbstractEnum.php
src/Type/Input/AbstractInput.php
src/Type/WPInterface/AbstractInterface.php
src/Type/WPInterface/Entry.php
src/Type/WPObject/Form/Form.php
src/Type/WPObject/Form/FormConfirmation.php
src/Type/WPObject/SubmissionConfirmation.php

Adds better type hints to our PHP Interfaces and Abstract classes, and as a result backfills several missing descriptions unearthed by the new hints.
While I'm not ready to migrate this over to the Plugin Boilerplate's abstracts, I can at least backport nonbreaking enhancements.
 

chore: better type hints and backfill missing descriptions
