src/Types/Field/RadioField.php
The trailing comma was preventing me from activating the plugin — with this removed, the plugin works and fields are also queryable which was an issue using the [0.1.0](https://github.com/harness-software/wp-graphql-gravity-forms/releases/tag/0.1.0) release for me.
=> Fixed syntax error.

src/Types/Union/ObjectFieldValueUnion.php
Same fix as https://github.com/harness-software/wp-graphql-gravity-forms/commit/9514feeacf783c386b769fec437b289076d17305#diff-a467d2c9aa8973439deb3536c75bcda4, this function was missed.
See https://github.com/wp-graphql/wp-graphql/releases v0.4.0
=> Fixed TypeRegistry class breaking change in wp-graphql v0.4.0+.

src/Mutations/UpdateDraftEntryNameFieldValue.php, src/Types/Field/FieldValue/NameFieldValue.php, src/Types/Input/NameInput.php, src/WPGraphQLGravityForms.php
This PR adds the `UpdateDraftEntryNameFieldValue` mutation. 
Based on [Twansparant's comment](https://github.com/harness-software/wp-graphql-gravity-forms/issues/17#issuecomment-634641265).
=> Add UpdateDraftEntryNameFieldValue mutation

src/Mutations/UpdateDraftEntryTimeFieldValue.php, src/Types/Field/TimeField.php, src/WPGraphQLGravityForms.php
This PR adds `UpdateDraftEntryTimeFieldValue` mutation.
Additionally, it adds `timeFormat` to the list of `TimeField` object fields. While other GF properties are missing (and should be added in a separate PR), I felt this was necessary for developers to use `UpdateDraftEntryTimeFieldValue`, as the timeFormat determines whether you want the input value to be submitted as `23:01` or `11:01 PM`.
=> Add UpdateDraftEntryTimeFieldValue mutation

src/Types/Field/FileUploadField.php
This pr adds missing properties to the `FileUploadField`.
Specifically, `allowedExtensions`, `maxFiles`, `maxFileSize` and `multipleFiles` are now available.
=> Add missing properties to FileUploadField

src/Connections/FormFieldConnection.php
This pr adds the `entries` connection to the `gravityFormsForm` query.
While it makes sense to use  `gravityFormsEntries` when you don't really care about the form context, this reduces the number of queries you need for contextual logic (e.g. if `limitEntriesCount` has been met, or if you want to display a user's previous entries along with the form itself).
=> Add `entries` connection to `gravityFormsForm` query

src/Types/Field/FieldValue/AddressFieldValue.php, src/Types/Field/FieldValue/DateFieldValue.php, src/Types/Field/FieldValue/EmailFieldValue.php, src/Types/Field/FieldValue/MultiSelectFieldValue.php, src/Types/Field/FieldValue/NameFieldValue.php, src/Types/Field/FieldValue/NumberFieldValue.php, src/Types/Field/FieldValue/PhoneFieldValue.php, src/Types/Field/FieldValue/SelectFieldValue.php, src/Types/Field/FieldValue/SignatureFieldValue.php, src/Types/Field/FieldValue/TimeFieldValue.php, src/Types/Field/FieldValue/WebsiteFieldValue.php
Address #16 .
This PR implements checks whether the FieldValue exists in `$entry` before trying to return the value. Prevents all those unnecessary error_log warnings when you're doing mutations on a single field.
**Note**: I opted for using `array_key_exists( $field['id'], $entry )` over `isset( $entry[ $field['id'] )`, as I feel it is more robust. That said, I did not change the few `{fieldtype}Field.php` that already use `isset`. If the maintainers have a preference for one or the other, I'm happy to switch this pr to use `isset()` or update the other files to use `array_key_exists`.
I _had to_ change the preexisting SignatureFieldValue check. since `! $entry[ $field['id'] ]` isnt the same as either `array_key_exists` or `isset`.
=> Check if FieldValue exists in $entry before trying to return it. 

src/Types/ConditionalLogic/ConditionalLogicRule.php
Some `fieldId`s that can be targeted with conditional logic are subfields (eg: `id: 5.1`), hence 'Float' is the required type.
=> Change Conditional Logic `fieldId` to Float

src/Mutations/DraftEntryUpdater.php
Correctly passes `$form_id` to `get_form_unique_id()` when one doesn't already exist in the `$submission` object.
- pass `$form_id` instead of `$draft_entry['form_id'] to `get_form_unique_id().
=> Bugfix: pass $form_id to `get_form_unique_id()`

src/Mutations/SubmitDraftEntry.php
To allow Post Creation to work, the form needs to have a valid page number. Since, the `pageField` is used for display purposes only, we need to artificially set it in `SubmitDraftEntry`.
- [New] Sets the form pageNumber to the last page on `submitGravityFormsDraftEntry`, to avoid post creation validation issues.
=> Set page number on submission

src/Types/Field/FieldValue/ListFieldValue.php
Previously, a PHP Warning would be thrown if `listFieldValue` was null or empty. This PR checks to see if a value is set, and returns early if it isnt.
- [Bugfix] Return early if `listFieldValue` is null or empty.
=> Return early if listFieldValue is null or empty.

src/Mutations/UpdateDraftEntrySignatureFieldValue.php, src/Types/Field/FieldValue/SignatureFieldValue.php
This PR
- Passes correct field id in `delete_previous_signature_image()`, as they werent deleting previously.
- Uses `$field->get_value_url()` to fetch the signature url, as `gf_signature()->get_signature_url()` is deprecated.
**Fixes** #64 
- [Bugfix] Correctly deletes old signature images when a new one is added to the `draftEntry.
- [Bugfix] Fixes deprecation notice from `gf_signature()->get_signature_url()`.
=> Various GFSignature fixes.

src/DataManipulators/FieldsDataManipulator.php, src/Mutations/UpdateDraftEntryListFieldValue.php, src/Types/Field/FieldValue/ListFieldValue.php, src/Types/Field/FieldValue/ListInputValue.php, src/Types/Input/ListInput.php
Previously, the array values saved to `listField` had an extra level that prevented GF from reading the entry value. This PR fixes that, while renaming some of the GraphQL field properties.
Also, since we're sanitizing the values, we're suppressing the PHPCS notice about using `serialize()`.
**Fixes**: #63 
- [Bug fix] Ensures single-column `listFields` have a set `choices` property, to prevent inconsistent behavior when saving values.
- [Bug fix] Fixed the `listFieldValue` array structure, so it can be properly read by GF.
- [Deprecation] The `input.value.values` property on `updateDraftEntryListFieldValue` has been deprecated. Going forward, please use `input.value.rowValues`.
- [Deprecation] The `ListFieldValue.listValues.value` property has been deprecated. Going forward, please use …
=> [Bugfix] Change listFieldValue array structure

src/Types/Field/FieldProperty/PasswordInputProperty.php
Adds `isHidden` property to PasswordInputProperty.
- [Feature] Add `isHidden` property to `PasswordInputProperty`.
=> Add isHidden property to PasswordInputProperty

src/Types/Field/FieldValue/ConsentFieldValue.php
The `value` property on `ConsentFieldValue`' was a conflicting type (boolean). This PR changes the `value` to `String` and returns the consent message (what GF does).
=> Fix ConsentFieldValue type conflict by changing value to string

src/Types/Form/FormNotificationRouting.php
The `fieldId` on `FormNotificationRouting` was accidentally returning a `String`. This fixes it so it returns type `Int`.
=> fix: Make FormNotificationRouting `fieldId` type int

src/DataManipulators/FormDataManipulator.php
The `FormDataManipulator` was converting form values for `limitEntriesCount`, `scheduleEndHour` and `scheduleEndMinute` to booleans, when they should be `Int`. This fixes that.
=> fix: Ensure missing `limitEntriesCount`, `scheduleEndHour` and `scheduleEndMinute` are type `int`.

src/Connections/EntryFieldConnection.php
#80 used v0.4.0 as its base and accidentally removed the include for `ObjectFieldUnion`. This restores it.
=> Restore ObjectFieldUnion includes

src/Mutations/AbstractMutation.php, src/Mutations/UpdateDraftEntryEmailFieldValue.php
Use `sanitize_text_field()` instead of `sanitize_email()` on email values, to allow failing emails to be passed to the server and validated.
Fixes:  
#87 
- Bugfix: Use `sanitize_text_field()` instead of `sanitize_email()` on email values, to allow failing emails to be passed to the server and validated.
- [x ] My code is tested to the best of my abilities.
=> fix: sanitize email values as text to allow validation.

README.md, src/Mutations/AbstractMutation.php, src/Mutations/SubmitForm.php, src/Mutations/UpdateDraftEntry.php, src/Mutations/UpdateDraftEntryEmailFieldValue.php, src/Mutations/UpdateEntry.php, src/Types/Input/EmailInput.php, src/Types/Input/FieldValuesInput.php, src/WPGraphQLGravityForms.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php
Email confirmation  was moved server-side in v0.4.0, but there was no way to input a confirmation value to the mutation. This PR changes all relevant mutations to take an `emailValues` input with a `value` and `confirmationValue` property.
Fixes: #90 
Feature (breaking): Support email confirmation on mutations.
=> feature!:add email confirmation

src/Mutations/AbstractDraftEntryUpdater.php
`UpdateDraftEntry{type}FieldValue` mutations were missing the field id for associated errors. This PR corrects that.
- Return field id for `UpdateDraftEntry{type}FieldValue` errors
=> fix: return field id for DraftEntryUpdater `errors`

src/Mutations/SubmitDraftEntry.php
Fixes a PHP Notice when no `entry_id` is returned in `submitGravityFormsDraftEntry`.
- Bug fix: Fix PHP Notice when no `entry_id` is returned in `submitGravityFormsDraftEntry`.
=> fix: prevent PHP notice when no `entry_id` is returned in SubmitDraftEntry

src/Types/Field/FieldProperty/AddressInputProperty.php, src/Types/Field/FieldProperty/NameInputProperty.php, tests/wpunit/AddressFieldTest.php
Although not part of the Gravity Forms API, the `key` property on `AddressInput` and `NameInput` is essential for for indicating which fieldValue corresponds to the subfields. This PR undeprecates the property.
- Bugfix: Undeprecate `key` property on `AddressInput` and `NameInput` fields.
=> Undeprecate `key` property on AddressInput and NameInput

src/Types/Field/AddressField.php, src/Types/Field/ChainedSelectField.php, src/Types/Field/CheckboxField.php, src/Types/Field/FieldProperty/AbstractProperty.php, src/Types/Field/FieldProperty/AddressInputProperty.php, src/Types/Field/FieldProperty/ChainedSelectChoiceProperty.php, src/Types/Field/FieldProperty/ChainedSelectInputProperty.php, src/Types/Field/FieldProperty/CheckboxInputProperty.php, src/Types/Field/FieldProperty/ChoiceProperty.php, src/Types/Field/FieldProperty/ChoicesProperty.php, src/Types/Field/FieldProperty/InputProperty.php, src/Types/Field/FieldProperty/InputsProperty.php, src/Types/Field/FieldProperty/ListChoiceProperty.php, src/Types/Field/FieldProperty/NameInputProperty.php, src/Types/Field/FieldProperty/PasswordInputProperty.php, src/Types/Field/FieldProperty/RadioChoiceProperty.php, src/Types/Field/ListField.php, src/Types/Field/NameField.php, src/Types/Field/PasswordField.php, src/Types/Field/RadioField.php, vendor/composer/InstalledVersions.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php, vendor/composer/installed.php
Refactors `FieldProperty` types to use AbstractProperty.
- Housekeeping: Refactors `FieldProperty` types to use AbstractProperty.
=> refactor: Refactor field properties to use AbstractProperty

src/Mutations/AbstractMutation.php
This PR fixes a bug in the add_value_to_array() refactor, where `$values['id']` should have been `$field->id`.
=> fix: use $field->id to add_value_to_array()

src/Mutations/AbstractDraftEntryUpdater.php, src/Mutations/SubmitForm.php
This PR fixes two bugs with draft submissions.
- Bugfix: check for `resumeToken` before `entryId`, in the (rare) case that both are returned.
- Bugfix: ensure unset `$ip` is set to an empty string instead of `null`.
=> fix: check for resumeToken before entryId and set $ip to ''

CHANGELOG.md, README.md, readme.txt, src/WPGraphQLGravityForms.php, wp-graphql-gravity-forms.php
This pr is a hotfix release that fixes a fatal error when adding support for new fields with the `wp_graphql_gf_field_types` filter.
- Fixes a fatal error when adding support for new fields with the `wp_graphql_gf_field_types` filter.
=> v0.6.1 - Bugfix

src/Mutations/AbstractDraftEntryUpdater.php, src/Mutations/AbstractMutation.php, src/Mutations/CreateDraftEntry.php, src/Mutations/SubmitDraftEntry.php, src/Mutations/SubmitForm.php, src/Mutations/UpdateDraftEntry.php, src/Mutations/UpdateEntry.php, src/Settings/WPGraphQLSettings.php, vendor/composer/ClassLoader.php, vendor/composer/autoload_real.php
Backporting various bugfixes.
- fix: `updateGravityFormsEntry` mutation now correctly saves complex field values.
- fix: Pass previous value to `SignatureField`, so it can be deleted correctly.
- fix: Correctly set `graphql_connection_max_query_amount` to a minimum of 600.
- fix: `AbstractMutation::prepare_field_value_by_type()` no longer defaults to a string value`. A new filter `wp_graphql_gf_prepare_field_value` can be used for preparing values for custom GF fields.
- fix: Signature fields now validate correctly.
- dev: Add `wp_graphql_field_value_type` filter for setting a custom valid `FieldValueInput` type. 
- dev: Mutations now use `$this->form` consistently. As a result the arguments for `AbstractMutation::validate_field_value()` have changed.
=> Cherry-picking bugfixes

src/Mutations/AbstractMutation.php, src/Mutations/SubmitForm.php, src/Mutations/UpdateEntry.php, src/Types/Field/FieldProperty/ValueProperty/PostImageFieldValueProperty.php, src/Types/Field/FieldProperty/ValueProperty/PostImageValueProperty.php, src/Types/Field/FieldValue/PostImageFieldValue.php, src/Types/Field/PostImageField.php, src/Types/GraphQLInterface/FormFieldInterface.php, src/Types/Input/FieldValuesInput.php, src/Types/Input/PostImageInput.php, src/Types/Union/ObjectFieldValueUnion.php, src/WPGraphQLGravityForms.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php
Adds mutation support for post images
dev: Deprecated `adminOnly`, `allowsPrepopulate` and `inputName` on `PostImageField`.
feat: add `altText` to PostImage field values.
feat: add support for submitting and updating post image field values.
fix: Update linked posts on entry updates.
fix: passing wrong variable to deprecated `wp_graphql_gf_field_value_instances` filter.
=> Post image field mutations

src/Mutations/SubmitForm.php, src/Mutations/UpdateDraftEntry.php
`sourceUrl` was not passed correctly, causing the `updateDraftEntry` and the `submitForm` mutations to fail.
This PR sets the correct `sourceUrl` values, and adds `sourceUrl` to the mutation `input`.
- fix: `sourceUrl` not passed correctly to `updateDraftEntry` and `submitGravityFormsForm`. 
- feat: add `sourceUrl` to `updateDraftEntry` and `submitGravityFormsForm` inputs.
=> fix: sourceUrl updating

src/Utils/GFUtils.php
`GFUtils::get_forms()` was incorrectly using `GFAPI::get_form()` instead of `GFUtils::get_form()`. The latter is required so we can apply the gf filters on the return object, and catch graphql errors.
- fix: consistently apply GF filters and error-checking to `GFUtils::get_forms()`
=> fix: use get_form() wrapper to include filters and error checks

src/Connections/FieldConnections.php, src/Data/Loader/EntriesLoader.php, src/Data/Loader/FormsLoader.php, src/DataManipulators/DraftEntryDataManipulator.php, src/DataManipulators/EntryDataManipulator.php, src/DataManipulators/FieldsDataManipulator.php, src/DataManipulators/FormDataManipulator.php, src/Interfaces/DataManipulator.php, src/Mutations/AbstractDraftEntryUpdater.php, src/Mutations/SubmitDraftEntry.php, src/Mutations/SubmitForm.php, src/Mutations/UpdateDraftEntry.php, src/Mutations/UpdateEntry.php, src/Types/Entry/Entry.php, src/Types/Entry/EntryForm.php, src/Types/Form/Form.php, src/WPGraphQLGravityForms.php, vendor/composer/InstalledVersions.php, vendor/composer/installed.php
This PR converts data manipulators to static functions. This means we can call those `manipulate()` functions without passing an instantiated class. In addition to simplifying the code complexity, this will make it easier to switch those classes for WPGraphQL models.
- dev: make DataManipulator functions static
=> dev: make DataManipulator functions static

src/Connection/FormFieldConnections.php
Adds a `page` arg to all `formField` connections, allowing filtering form fields by page.
- feat: add `page` filter to `formFields`.
=> feat: filter `formFields` by page

src/Type/WPInterface/FormField.php
`gatsby-source-wordpress` currently [can't handle non-nullable enums](https://github.com/gatsbyjs/gatsby/issues/34489).
Until that gets fixed, field `type` on interface `FormField` has been changed to a nullable type.
This _is not_ a breaking change. However, reverting the field back to `non_null` **would be considered breaking**  
Fixes #202 .
- fix: make `formField.type` nullable, to play nicely with `gatbsy-source-wordpress`.
=> fix: make `formField.type` nullable (for gatsby-source-wordpressl)

src/Extensions/GFChainedSelects/Type/WPObject/FormField/FieldProperty/PropertyMapper.php, src/Type/WPObject/FormField/FieldProperty/ChoiceMapper.php, src/Type/WPObject/FormField/FieldProperty/InputMapper.php, tests/_support/TestCase/FormFieldTestCase.php
WPGraphQL v1.6.11 causes `DUPLICATE_FIELD` errors to appear on formField queries.
This PR fixes those duplicate objects, by locally tracking which `{type}FieldChoice` /`{type}InputProperty` have already been queued to register.
- fix: don't reregister GraphQL generated form field `{type}FieldChoice` and `{type}InputProperty`.
=> Fix: Dont reregister duplicate fields (WPGraphQL 1.6.11 compat)

src/Model/Form.php, src/Type/WPObject/Form/FormConfirmation.php, tests/wpunit/FormQueriesTest.php
Adds the `isActive` GraphQL field to `FormConfirmation`.
- feat: add field `isActive` to `FormConfirmation`.
=> feat: add field `isActive` to `FormConfirmation`

src/Type/Enum/PostFormatTypeEnum.php, vendor/composer/InstalledVersions.php, vendor/composer/installed.php
Prevents a PHP notice when `post-formats` aren't supported by the WP theme.
h/t @noshoesplease
Fixes #210 
- fix: Prevent a PHP notice caused when `post-formats` aren't supported by the WP theme.
=> fix: check for post-formats before adding them to `PostFormatTypeEnum`

docs/actions-and-filters.md, src/Model/DraftEntry.php, src/Model/SubmittedEntry.php, src/Mutation/SubmitForm.php
This PR addresses an issue where GF permissions are enforced on the `submitGfForm` payload, preventing non-authenticated users from seeing their submitted entry.
Fixes #222 
- feat: add `$resume_token` and `$draft_entry` arguments to `graphql_gf_can_view_draft_entries`.
- feat: add `$entry_id` and `$entry` arguments to `graphql_gf_can_view_entries`.
- fix: Use `graphql_gf_can_view_entries` filter to expose `submitGfFormMutation.entry` to non-authenticated users.
- [ x] My code follows the WordPress Coding Standards.
=> Expose entry to non-authenticated users in submit mutation

src/Data/Connection/FormsConnectionResolver.php, tests/wpunit/FormQueriesTest.php
This PR fixes the underlying logic used by FormsConnectionResolver, reducing the number of database queries and fixing `hasNextPage` and `hasPreviousPage` GraphQL values.
Fixes #150.
- fix: correctly return `hasNextPage` or `hasPreviousPage` on GfForm connections.
- dev: don't re-query database when calling `FormsConnectionResolver::get_ids()`.
=> FormsConnectionResolver fixes

.gitignore, src/Type/WPObject/FormField/FormFields.php, src/Utils/Utils.php
This PR renames the following fields:
- `ProductHiddenProductField` => `ProductHiddenField`
- `ProductSingleProductField` => `ProductSingleField`.
- `ShippingSingleShippingField` => `ShippingSingleField`. 
It also fixes an issue where the `FormFieldTypeEnum` for `calculation`, `hiddenproduct`, `singleproduct`, and `singleshipping` were missing.
- fix: dont hide pricing child types from `FormFieldTypeEnum`.
- fix!: Rename `{$type}Single{$type}Field` and `${type}Hidden{$type}Field` to `${type}SingleField` and `${type}HiddenField`, respectively.
=> Fix!: Rename pricing fields

readme.txt, src/Extensions/GFQuiz/GFQuiz.php, src/Extensions/GFQuiz/Type/WPObject/Form/FormQuiz.php, src/Model/Form.php, wp-graphql-gravity-forms.php
- Deprecate `graphql_gf_form_modeled_data_experimental` in favor of [`graphql_model_prepare_fields`](https://github.com/wp-graphql/wp-graphql/pull/2236). This bumps the minimum WPGraphQL version to v1.7.0
- Fixes an issue where QuizField resolvers were using the Form model, instead of the unmodeled source data.
=> Fix/Quiz form model 

src/Model/Form.php, src/Type/WPObject/Form/FormNotification.php
Confirmation and notification `isActive` is not stored by default, so we need to set the default to true.
Fixes #253 
- fix: Ensure `isActive` on Form confirmations and notifications defaults to `true`.
=> fix: confirmation/notification `isActive` should default to true

src/Extensions/WPGatsby/Settings.php, src/Extensions/WPGatsby/WPGatsby.php, vendor/composer/installed.php
This PR cleans up the logic used to populate the `log_gatsby_gf_action` setting, ensuring the correct array values are passed.
Closes #248
Primarily by the logic used by the setting checks.
1. Visit `mysite.com/wp-admin/options-general.php?page=gatsbyjs`
2. Uncheck all options shown for `Monitor Gravity Forms Actions`
3. Click save changes.
=> fix: ensure Action Monitor settings are populated

src/Type/WPObject/FormField/FieldProperty/FieldProperties.php
Correctly resolves the `NumberField.rangeMin` and `rangeMax` values.
h/t @natac13 
Previously, a min/max of 0 would return null, and numbers formatted as a `decimal_comma` would error.
=> fix: correctly resolve `rangeMin` and `rangeMax` values

src/Type/WPObject/Form/FormConfirmation.php, src/Type/WPObject/SubmissionConfirmation.php, tests/wpunit/SubmitDraftEntryMutationTest.php
- feat: add `isAutoformatted` to the `FormConfirmation` object.
- feat: add `pageId` and `queryString` fields and `Page` connection to `FormSubmission` object.
```graphql
mutation myMutation($input: SubmitGfFormInput!) {
submitGfForm(input: $input) {
confirmation {
page {
node {
databaseId
}
}
pageId
queryString
type
}
entry {
form {
confirmations {
isAutoformatted
}
}
}
}
}
```
=> feat: Add additional fields to `FormConfirmation` and `SubmissionConfirmation`

.dockerignore, bin/_lib.sh, bin/install-stan-env.sh, bin/install-test-env.sh, docker-compose.yml, docker/app.Dockerfile, docker/app.post-setup.sh, docker/app.setup.sh
Speeds up docker builds 
#266 
Stores the wordpress as a volume so the test image doesnt need to rebuild it.
- [] I have added unit tests to verify the code works as intended.
=> chore: optimize dockerfile

docs/submitting-forms.md
Adds some explanation, and usage examples of the `Upload` type.
Knowledge is power.
=> docs: Add usage example for file uploads

src/Data/Loader/DraftEntriesLoader.php, src/Data/Loader/EntriesLoader.php, src/Data/Loader/FormsLoader.php, tests/_data/config.php, tests/wpunit/EntryQueriesTest.php, tests/wpunit/FormQueriesTest.php
This PR fixes the logic used in the form/entry `DataLoader` classes, to ensure that non-existent objects return `null` instead of throwing an error.
Currently, querying for a non-existent `databaseId`s will throw a PHP or GraphQL error, instead of resolving to `null`.
See: https://wp-graphql.slack.com/archives/C01M7SGUGQL/p1657851805580839 
Instead of fetching all items and matching them to the requested `key`, only the requested objects are fetched. `Utils` methods are _not_  used, as we don't want to throw any errors.
Run the following query:
```graphql
{
gfForm(id: 999999999999, idType: DATABASE_ID) {
databaseId
}
gfEntry(id: 999999999999, idType: DATABASE_ID) {
id
}
}
```
=> Fix: Ensure DataLoaders return null

src/Extensions/GFChainedSelects/GFChainedSelects.php
This PR replaces the use of `graphql_gf_form_field_value_properties` by `GFChainedSelects` with `graphql_gf_form_field_value_fields`, and renames the hooked method and parameters to reflect this.
GFChainedSelects was still using the deprecated `graphql_gf_form_field_value_properties` hook. 
1. Run tests with WP debug enabled.
2. Confirm no PHP notices are printed to debug.log
=> fix: remove use of deprecated `graphql_gf_form_field_value_properties`

src/Registry/FieldChoiceRegistry.php, src/Registry/FieldInputRegistry.php, src/Registry/TypeRegistry.php, src/Type/WPInterface/FieldChoice.php, src/Type/WPInterface/FieldChoiceSetting/ChoiceWithName.php, src/Type/WPInterface/FieldInputProperty.php, src/Type/WPInterface/FieldValue/FieldValueWithChoice.php, src/Type/WPInterface/FieldValue/FieldValueWithInput.php, src/Type/WPObject/FormField/FieldDataPolicy.php, src/Type/WPObject/FormField/FieldValue/FieldValues.php, src/Type/WPObject/FormField/FieldValue/ValueProperty/CheckboxFieldValue.php, src/Type/WPObject/FormField/FormFields.php, tests/wpunit/CheckboxFieldTest.php, tests/wpunit/PostCategoryCheckboxFieldTest.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php, vendor/composer/installed.php
Adds `connectedChoice` and `connectedInput` to `checkboxFieldValue` types.
Make it easier to understand the context of a checkbox value without needing to use the `inputId` in a form lookup.
Uses `FieldValueWithChoice` and `FieldValueWithInput` interfaces.
=> feat: field value connections

.github/workflows/code-quality.yml, .github/workflows/code-standard.yml, .github/workflows/integration-testing.yml, .github/workflows/schema-linter.yml
Use `safe to test ✔` for running GH workflows that require secrets
`pull_request` doesn't have access to secrets, and `pull_request_target` alone is unsafe.
see: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
=> chore: use label to run github workflows with secrets

.phpcs.xml.dist, CHANGELOG.md, README.md, phpstan/constants.php, readme.txt, src/Data/Connection/EntriesConnectionResolver.php, vendor/composer/installed.php, wp-graphql-gravity-forms.php
This PR checks and reports if an unsupported plugin dep _version_ is found. 
It also drops support for WPGraphQL < `v1.9.0`
Part of #310 
- feat!: Update minimum required WPGraphQL version to v1.9.0.
- feat: Check if plugin dependences meet the minimum version requirements.
=> feat!: Check dep versions and update minimum required WPGraphQL version to v1.9.0.

CHANGELOG.md, src/Model/Form.php
Ensures `personalData` is a non-empty array before attempting to resolve it on the `Form` model.
The GF form `getter` ensures the value will be set, so `?? null`, doesn't have its intended effect.
=> fix: Check for falsey `personalData` when resolving the form model.

docs/submitting-forms.md
Changes the `listValues` input example to use a long-form array syntax, instead of the existing shorthand value.
h/t @tomdofuture
Our documentation is to show how best to use our schema, not now to write GraphQL queries, and list fields, more often than not are going to take multiple `rowValues` anyway.
Closes #326 
See the changeset.
=> docs: use full syntax for listValues example

CHANGELOG.md, src/Registry/TypeRegistry.php, src/Type/Enum/AddressFieldProvinceEnum.php, src/Type/Enum/AddressFieldStateEnum.php, src/Type/WPInterface/FieldSetting/FieldWithAddress.php, tests/_support/Helper/GFHelpers/ExpectedFormFields.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php, vendor/composer/installed.php
Adds the `AddressFieldProvinceEnum` and `AddressFieldStateEnum` to the schema, and changes `AddressField.defaultProvince` and `AddressField.defaultState` to use those enums
Closes #320
- dev!: change `AddressField.defaultState` and `AddressField.defaultProvince` to respective `AddressField{Province|State}Enum`.
These enums use the full `UPPERCASE_NAME`, so if you want to reuse them in a frontend dropdown, you can just map the generate enum types to `Title Case Name`.
=> dev!: change `AddressField.defaultState` and `defaultProvince` to enum

.github/workflows/code-quality.yml, .github/workflows/code-standard.yml, .github/workflows/integration-testing.yml, .github/workflows/schema-linter.yml, CHANGELOG.md, bin/run-docker.sh
Reverts PHP 8.1 compatibility.
Closes #339
Reopens #299 
GF is [not yet compatible with PHP 8.1](https://docs.gravityforms.com/gravity-forms-and-php-8-1-compatibility/) causing #339 to fail.
Reverts 8.1 bumps to 8.0
=> chore: revert PHP 8.1 Compatibility

CHANGELOG.md, docs/submitting-forms.md
This PR replaces `formId` with `id` in the example submission mutations.
Attempting to submit a mutation using `formId` gives this error:
`There was an error submitting the form: [GraphQL] Field SubmitGfFormInput.id of required type ID! was not provided. [GraphQL] Field "formId" is not defined by type SubmitGfFormInput.`
No implementation, just updating the docs to reflect the correct mutation.
=> docs: replace formId with id in examples

CHANGELOG.md, src/Mutation/SubmitForm.php
Reimplements #345 on `v0.11.x`
Fixes so IP is saved properly and no longer overwritten by the source URL.
Closes #344 
I couldn't rebase #345 onto `main` for some reason, even though `SubmitMutation.php` had no merge conflicts. The code here is identical and full props go to @marcusforsberg
=> fix: properly store IP when submitting an entry

docs/form-field-support.md, docs/querying-entries.md, docs/querying-formfields.md, docs/querying-forms.md, src/Type/WPInterface/FormField.php, tests/_support/TestCase/FormFieldTestCase.php, tests/wpunit/CaptchaFieldTest.php, tests/wpunit/EntryQueriesTest.php, tests/wpunit/ProductCalculationFieldTest.php, tests/wpunit/ProductHiddenFieldTest.php, tests/wpunit/ProductPriceFieldTest.php, tests/wpunit/ProductRadioFieldTest.php, tests/wpunit/ProductSelectFieldTest.php, tests/wpunit/ProductSingleFieldTest.php, tests/wpunit/SubmitFormMutationTest.php
Deprecates the `FormField.id` GraphQL field in favor of `FormField.databaseId`.
In a future release, we need to change the `id` to be a Relay `ID`, so we can implement #298 and make the connection fully Relay compliant (see #335)
=> feat: deprecate `FormField.id` in favor of `databaseId`

CHANGELOG.md, src/Registry/FieldChoiceRegistry.php, src/Registry/FieldInputRegistry.php, tests/_support/TestCase/FormFieldTestCase.php
This PR stores the types registered by `FieldInputRegistry` and `FieldChoiceRegistry` in a local cache variable, to 
to prevent the registration of duplicate/nonexistent `FormFieldChoice` and `FormFieldInputProperty` types.
Additionally a test has been added to ensure GraphQL debug messages are caught before release.
Previously there was a bug where child types (e.g. `OptionCheckboxField` would try to register their input property types with a nonexistent parent interface. By checking a local store we both save the extra check to the TypeRegistry and ensure that only actual types are used for parent interfaces.
The classes now have a `$registered_types` static variable which is used for storage and checking.
The test assert is not applied to mutations (yet), since we intentionally output …
=> fix: use local store for `FieldInputRegistry` and `FieldChoiceRegistry` to prevent duplicate/nonexistent type registration

.github/workflows/schema-linter.yml, CHANGELOG.md
Suppresses the following [error](https://github.com/harness-software/wp-graphql-gravity-forms/actions/runs/4866297468/jobs/8677669607?pr=356):
`The field `FormFieldConnection.pageInfo` is missing a description. fields-have-descriptions`
The error is is because we're no longer using WPGraphQL's new connection interfaces until we can make `FormField.id` compliant with the spec. Once that changes, we can remove this `ignore` rule.
=> ci: ignore `graphql-schema-linter` error about missing `FormFieldConnection.pageInfo` description

CHANGELOG.md, docs/submitting-forms.md
Add missing documentation regarding using `productValues` input when submitting forms.
Closes #357
=> docs: add `productValues` input usage

CHANGELOG.md, src/Data/Connection/EntriesConnectionResolver.php, src/Data/Connection/FormsConnectionResolver.php, src/Mutation/AbstractMutation.php, src/Mutation/DeleteEntry.php, src/Mutation/SubmitForm.php, src/Mutation/UpdateEntry.php, src/Type/WPObject/Entry/DraftEntry.php, src/Type/WPObject/Entry/SubmittedEntry.php, src/Type/WPObject/Form/Form.php, src/Utils/Utils.php
This PR refactors the `AbstractMutation::get_entry_id_from_id()` and `AbstractMutation::get_form_id_from_id()` into `Utils` methods, and changes the plugin to use those new methods.
As a result, `GfEntriesConnectionWhereArgs.formIds` and `GfFormsConnectionwhereArgs.formIds` now accept either a global or database ID, and other form/entry ID inputs will work more reliably if no `idType` is provided.
Closes #308
=> dev: refactor indeterminate ID resolution

CHANGELOG.md, src/Type/WPObject/Entry/SubmittedEntry.php
This PR replaces the usage of `WPGraphQL\Data\DataSource::resolve_post_object()` with `$context->get_loader('post')`.
`resolve_post_object()` was deprecated in 0.8.4, but only had notices exposed in https://github.com/wp-graphql/wp-graphql/pull/2776
=> dev: remove call to deprecated `resolve_post_object()`

CHANGELOG.md, src/Data/Connection/FormsConnectionResolver.php
This PR primes the `FormsLoader` when using the `FormsConnectionResolver`.
Since GF only allows you to query for the entire form, theres no difference between Connection Resolver query and the actual model population. By priming the dataloader cache, we can prevent the unnecessary extra database queries.
=> dev: Prime the FormsLoader when querying form connections

composer.json, composer.lock, src/Type/WPInterface/Entry.php, vendor/composer/installed.php
This pr switches `axpress/wp-graphql-cs` from the `dev-develop` branch back to the `1.0.0-beta` release.
It also primes the `FormsLoader` when forms are fetched in the `FormFieldsConnectionResolver`
These were unintentionally omitted from #369 and #368, respectively.
=> chore: cleanup

.github/workflows/code-quality.yml, .github/workflows/schema-linter.yml, .github/workflows/upload-schema-artifact.yml, CHANGELOG.md, docker-compose.yml
Fixes the workflows by locking `mariadb:10`
MariaDB v11 is not yet compatible with wordpress.
=> ci: lock mariadb to v10

CHANGELOG.md, composer.lock, tests/_data/config.php, tests/acceptance.suite.dist.yml, vendor/composer/installed.php
Sets the WPLoader `loadOnly` property to `true` in the Codeception Acceptance suite config file.
Solution provided by @lucatume in https://github.com/lucatume/wp-browser/issues/614#event-10342587864
This oversight in the config file was causing upstream deprecations to make Codeception fail. E.g. https://github.com/AxeWP/wp-graphql-gravity-forms/pull/366
=> tests: set `WPLoader.loadOnly: true` in acceptance suite

.github/workflows/code-quality.yml, .github/workflows/code-standard.yml, .github/workflows/integration-testing.yml, .github/workflows/schema-linter.yml, CHANGELOG.md, README.md, bin/run-docker.sh, docker-compose.yml, readme.txt, wp-graphql-gravity-forms.php
Changes the ci actions, testing matrix, and plugin headers to support WordPress 6.3.1 and PHP 8.1.
=> ci: test against WP 6.3 + PHP 8.1

.github/workflows/integration-testing.yml
Limits CI testing matrix to only test PHP 8.1 on WordPress versions 6.2+ (since GF + WP is not compatible with earlier versions).
=> ci: only run PHP 8.1 against WP 6.2+

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/workflows/schema-linter.yml, CHANGELOG.md, README.md, composer.json, docker/app.Dockerfile, docker/testing.Dockerfile, docs/form-field-support.md, docs/recipes/register-custom-field-value-inputs.md, docs/recipes/register-custom-form-field.md, docs/submitting-forms.md, readme.txt, src/UpdateChecker.php, vendor/composer/installed.php, wp-graphql-gravity-forms.php
=> chore: update repo links and readme

CHANGELOG.md, src/Extensions/GFQuiz/Type/WPObject/Entry/EntryQuizResults.php
Passes the GF entry array to the `QuizResults` resolver, instead of the `SubmittedEntry` object.
`SubmittedEntry` doesnt include the quiz results.
=> fix: Pass the GF entry to the `QuizResults` resolver

CHANGELOG.md, src/Type/WPInterface/FieldWithInputs.php
This PR fixes `formField.input` returning `null` for `EmailField` types that have Email Confirmation disabled.
Closes #392 
`GF_Field_Email` only uses the `inputs` property for fields with Email Confirmation, so we're manually populating the array with "Default" values.
The `autocompleteAttribute` field is not saving in GF v2.8.x. Reported upstream. When assigned programmatically, the response works.
=> fix: ensure `EmailField` inputs are hydrated when Email Confirmation is disabled.

CHANGELOG.md, src/Data/Connection/FormFieldsConnectionResolver.php, tests/wpunit/CaptchaFieldTest.php
This PR fixes the `FormFieldConnectionResolver` so the form fields filtered by the connection `where` args are used, instead of the pre-filtered values.
Closes #392
=> fix: correctly use filtered form fields when preparing the connection data.

CHANGELOG.md, composer.json, composer.lock, src/Interfaces/Enum.php, src/Registry/FormFieldRegistry.php, vendor/composer/installed.php, wp-graphql-gravity-forms.php
Fixes `PHPCompatibility` dependency to use `dev-develop` instead of `dev-master`.
The v10.0 branch is `develop` not master.
=> chore: fix phpcompatibility

CHANGELOG.md, phpstan.neon.dist, src/Data/Connection/EntriesConnectionResolver.php, src/Data/Connection/FormsConnectionResolver.php, src/Data/EntryObjectMutation.php, src/Data/FieldValueInput/AbstractFieldValueInput.php, src/Data/FieldValueInput/AddressValuesInput.php, src/Data/FieldValueInput/CheckboxValuesInput.php, src/Data/FieldValueInput/ConsentValueInput.php, src/Data/FieldValueInput/EmailValuesInput.php, src/Data/FieldValueInput/FileUploadValuesInput.php, src/Data/FieldValueInput/ImageValuesInput.php, src/Data/FieldValueInput/ListValuesInput.php, src/Data/FieldValueInput/NameValuesInput.php, src/Data/FieldValueInput/ProductValueInput.php, src/Data/FieldValueInput/ValueInput.php, src/Model/FormField.php, src/Mutation/UpdateDraftEntry.php, src/Mutation/UpdateEntry.php, src/Registry/FieldChoiceRegistry.php, src/Registry/FieldInputRegistry.php, src/Utils/GFUtils.php, vendor/composer/installed.php
This PR adds iterable typehints whereever possible to doc-blocks, and restores the sniff to PHPStan
Code quality.
=> chore: use iterable type hints

src/Data/Connection/FormFieldsConnectionResolver.php, tests/wpunit/EmailFieldTest.php, tests/wpunit/EmailFieldWithConfirmationTest.php, tests/wpunit/FormConnectionQueriesTest.php, tests/wpunit/FormFieldConnectionQueriesTest.php
This PR:
- Fixes FormField backwards pagination 
- Fixes FormField filters
- Backfills tests for FormField connections
=> fix: backwards pagination and filtering in `FormFieldsConnectionResolver`

CHANGELOG.md, src/Data/EntryObjectMutation.php, src/Data/FieldValueInput/RadioValueInput.php, src/Model/FormField.php, src/Mutation/UpdateEntry.php, src/Type/WPObject/FormField/FieldValue/FieldValues.php, tests/_support/Helper/Wpunit.php, tests/wpunit/RadioFieldOtherChoiceTest.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php, vendor/composer/installed.php
This PR adds explicit handling for `gf_other_choice` and `input_%id%_other` on RadioField submissions.
This is a _nonbreaking_ change.
After GF made internal changes to their state management in 2.7 (2.6?), passing a custom choice value would fail validation. However we had no tests in place to let us know this stopped working 🤦.
This was reported as a documentation issue in #390 and #417 , but it was actually a bug.
The submission still takes a `value` as usual, If the Radio field has choices enabled, then we set the necessary GF_Entry input values.
=> fix: handle RadioField submission values when using a custom "other" choice.

CHANGELOG.md, src/Data/Connection/FormFieldsConnectionResolver.php, tests/wpunit/FormFieldConnectionPageFilterTest.php, tests/wpunit/FormFieldConnectionQueriesTest.php
This PR changes the behavior of the `pageNumber` filter on Form Fields connection, so that `GF_Field_Page` is included in the results for the previous `pageNumber`.
This is a **breaking** change.
As noted in https://github.com/AxeWP/wp-graphql-gravity-forms/issues/208#issuecomment-2043083723, the `Page` field includes the data required to create back/next buttons for the page number _preceeding_ it. But because the `pageNumber` is is for the _upcoming_ page, it misses the field field.
=> fix!: Keep `PageField` with previous page data when filtering `formFields` by `pageNumber`.

CHANGELOG.md, docs/submitting-forms.md, src/Connection/FormFieldsConnection.php, src/Mutation/SubmitForm.php, src/Utils/GFUtils.php, tests/_support/Helper/GFHelpers/PropertyHelper.php, tests/wpunit/FormFieldConnectionPageFilterTest.php, tests/wpunit/SubmitFormMultipageTest.php
This PR:
- fixes and issue where the GF state wasnt getting flushed if multiple `GFUtils::submit_form()` calls are made.
- adds the `targetPageNumber` (int) and `targetPageFormFields` (Form Field connection) to `SubmitGfFormPayload` for better multi-page form support.
- Backfills tests for `sourcePage` and `targetPage`.
- Adds docs for submitting multi-page forms.
Fixes #208
=> feat: multi-page form submission improvements

CHANGELOG.md, README.md, composer.lock, tests/wpunit/FormFieldConnectionPageFilterTest.php, tests/wpunit/GFUtilsTest.php, tests/wpunit/RadioFieldOtherChoiceTest.php, tests/wpunit/SubmitFormMultipageTest.php, vendor/composer/installed.php
- Updates composer dev-deps
- Backfills GFUtils tests, and formats.
- Replaces the Slack link with Discord.
=> chore: update deps, backfill tests, cleanup readme links

CHANGELOG.md, src/Extensions/GFSignature/Data/FieldValueInput/SignatureValuesInput.php
This PR changes Signature uploading to use `\WP_Filesystem` instead of `file_put_contents()`
Compliance with wpcs/pcp
=> dev: use WP_Filesystem for Signature Field uploads

CHANGELOG.md, src/Registry/FormFieldRegistry.php, src/Type/WPInterface/FieldSetting/FieldWithProductField.php, tests/wpunit/OptionCheckboxFieldTest.php, tests/wpunit/OptionRadioFieldTest.php, tests/wpunit/OptionSelectFieldTest.php, tests/wpunit/QuantityHiddenFieldTest.php, tests/wpunit/QuantityNumberFieldTest.php, tests/wpunit/QuantitySelectFieldTest.php
This PR deprecates the (int) `GfFieldWithProductFieldSetting.productField` in favor of (ProductField) `.connectedProductField`.
=> feat: Replace `GfFieldWithProductFieldSetting.productField` with  `.connectedProductField`.

CHANGELOG.md, bin/run-docker.sh, composer.json, composer.lock, src/Autoloader.php
This PR updates the `Autoloader` to check if our main `GF` class is already loaded, before attempting to load the autoloader
If the entire package is loaded as a dependency, it's possible the autoloader will be generated higher up in the tree. 
Fixes #439 
Instead of coupling this to Composer, we use a `class_exists()` check.
=> fix: check if classes are already loaded before attempting to autoload them.

CHANGELOG.md, src/Autoloader.php, src/Type/WPObject/FieldError.php, src/Type/WPObject/Order/OrderItem.php
This PR:
- fix: Fix typo in Autoloader release URL.
- fix: Ensure a valid source ID exists before attempting to resolve a `connectedFormField`.
These are bugs in code introduced in 0.13.0.
=> fix: various 0.13.0 regressions
